name: Docker Image CI
on: [push]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag r4mmer/ipython:$IMAGE_TAG
        docker tag r4mmer/ipython:$IMAGE_TAG r4mmer/ipython:latest
    - name: Push image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        docker push r4mmer/ipython:$IMAGE_TAG
        docker push r4mmer/ipython:latest
